exclude:
  assetCategory:
    - ''
    - CASH & CASH EQUIVALENTS
    - CONVERTIBLE OR EXCHANGEABLE SECURITIES
    - CONVERTIBLE SECURITIES

  assetType:
    - EQUITY POOL FUNDS (CANADIAN)
    - FINANCIAL SERVICES - TRUSTS ETF (CANADIAN)
    - GLOBAL EQUITY INDEX ETF (US REGULATED)
    - INTERNATIONAL EQUITY FUND TRUST (CANADIAN)
    - INTERNATIONAL EQUITY FUND TRUST ETF (CANADIAN)
    - US EQUITY FUNDS (US REGISTERED)
    - US EQUITY INDEX ETF (US REGULATED)
    - AGENCY FOR INTL DEVELOPMENT BACKED DEBT
    - ASSET BACKED SECURITES (CANADIAN)
    - CANADIAN BOND FUND TRUST ETF  (CANADIAN)
    - CANADIAN BOND TRUST (CANADIAN)
    - CANADIAN GOVERNMENT BONDS
    - CMBS - CONDUIT
    - COMMIT TO PURCHASE FNMA POOLS
    - COMMIT TO PURCHASE GNMA POOLS
    - COMMIT TO PURCHASE GNMA(MULTI FAMILY) POOLS
    - FHLMC MULTICLASS
    - FHLMC POOLS
    - FNMA POOLS
    - FNMA REMIC
    - GLOBAL BOND FUNDS (CANADIAN)
    - GNMA MULTI FAMILY POOLS
    - GNMA SINGLE FAMILY POOLS
    - GOVT OF CANADA - AGENCIES (CANADIAN)
    - GOVT OF CANADA - DIRECT (CANADIAN)
    - GOVT OF CANADA - INFLATION INDEXED (CANADIAN)
    - MORTGAGES (CANADIAN)
    - MUNICIPALS (CANADIAN)
    - NON-US GOV GUARANTEED BONDS - FINANCIAL
    - NON-US GOVERNMENT BONDS
    - NON-US GOVERNMENT BONDS - COVERED
    - NON-US GOVERNMENT PRIVATE PLACEMENTS
    - NON-US GOVT INFLATION LINKED SECURITIES
    - NHA (CANADIAN)
    - OTHER U.S. GOVT. OBLIGATIONS
    - PROVINCIALS - AGENCIES (CANADIAN)
    - PROVINCIALS (CANADIAN)
    - TAXABLE MUNICIPALS
    - TOTAL RETURN SWAPS
    - US AGENCIES
    - US FIXED INCOME ETF (US REGULATED)
    - US GOVERNMENTS

military:
  assetType:
    - AEROSPACE/DEFENSE
    - AEROSPACE & DEFENSE

oil:
  assetType:
    - COAL
    - ENERGY (CANADIAN)
    - EXPLORATION & PRODUCTION - UK
    - GAS
    - INTEGRATED OIL & GAS - UK
    - OIL & GAS
    - OIL & GAS SERVICES
    - OIL EQUIPMENT & SERVICES - UK
    - PIPELINES
    - NATURAL RESOURCES (CANADIAN)
    - PREFERRED STOCK - OIL & GAS

  description1:
    - PEMBINA PIPELINE CORP
    - XEBEC ADSORPTION INC
    - BHP BILLITON FINANCE USA LTD
    - BURLINGTON RESOURCES LLC
    - CANADIAN NATURAL RESOURCES LTD
    - CNOOC PETROLEUM NORTH AMERICA
    - EQUINOR ASA
    - SUNCOR ENERGY INC
    - TRANSCANADA PIPELINES LTD
    - UNITED UTILITIES PLC

mining:
  assetType:
    - GOLD MINING - UK
    - MINING
    - NON-FERROUS METALS - UK

  description1:
    - AGNICO EAGLE MINES LIMITED
    - ALAMOS GOLD INC NEW
    - ALEXCO RESOURCE CORP
    - AMERICAS GOLD AND SILVER CORP
    - ARGONAUT GOLD INC NEW
    - ASCOT RES LTD
    - B2GOLD CORP
    - BARRICK GOLD CORP
    - CAMECO CORP
    - CAPSTONE MINING CORP
    - CENTERRA GOLD INC
    - CHINA GOLD INTL RES CORP LTD
    - DENISON MINES CORP
    - ELDORADO GOLD CORP
    - ENDEAVOUR MINING CORPORATION
    - EQUINOX GOLD CORP
    - ERO COPPER CORP
    - FIRST MAJESTIC SILVER CORP
    - FIRST QUANTUM MINERALS LTD
    - FORTUNA SILVER MINES INC
    - FRANCO-NEVADA CORP
    - FREEGOLD VENTURES LTD
    - GALIANO GOLD INC
    - GOLDEN STAR RESOURCES LTD
    - GOLDMINING INC
    - GRAN COLOMBIA GOLD CORP
    - HUDBAY MINERALS INC
    - IAMGOLD CORP
    - INTL TOWER HILL MINES LTD NEW
    - IVANHOE MINES LTD
    - JAGUAR MINING INC
    - KINROSS GOLD CORP
    - KIRKLAND LAKE GOLD LTD
    - LA COMPAGNIE MINIERE DE
    - LABRADOR IRON ORE ROYALTY CORP
    - LITHIUM AMERICAS CORP NEW
    - LUCARA DIAMOND CORP
    - LUNDIN GOLD INC
    - LUNDIN MINING CORP
    - MAG SILVER CORP
    - MAJOR DRILLING GROUP INTL INC
    - NEW GOLD INC
    - NEW PACIFIC METALS CORP
    - NORTH AMERN CONSTR GROUP LTD
    - NORTHERN DYNASTY MINERALS LTD
    - NOVAGOLD RESOURCES INC
    - OCEANAGOLD CORP
    - ORLA MINING LTD
    - OSISKO GOLD ROYALTIES LTD
    - OSISKO MINING INC
    - PAN AMERICAN SILVER CORP
    - PLATINUM GROUP METALS LTD
    - PRETIUM RESOURCES INC
    - SABINA GOLD & SILVER CORP
    - SANDSTORM GOLD LTD
    - SEABRIDGE GOLD INC
    - SIBANYE GOLD LIMITED
    - SIERRA METALS INC
    - SILVERCORP METALS INC
    - SILVERCREST METALS INC
    - SSR MINING INC
    - TASEKO MINES LTD
    - TECK RESOURCES LTD
    - TERANGA GOLD CORP
    - TOREX GOLD RESOURCES INC
    - TREVALI MINING CORP
    - TURQUOISE HILL RESOURCES LTD
    - UR ENERGY INC
    - WALLBRIDGE MINING COMPANY LTD
    - WESDOME GOLD MINES LTD
    - WHEATON PRECIOUS METALS CORP
    - YAMANA GOLD INC

alternative:
  assetType:
    - ALTERNATIVE FUELS - UK
    - ENERGY - ALTERNATE SOURCES
    - LIMITED PARTNERSHIP - PUBLIC EQUITY

  description1:
    - IBERDROLA INTERNATIONAL BV

banking:
  assetType:
    - BANKS
    - BANKS - UK
    - BANKS (CANADIAN)
    - CONSUMER FINANCE - UK
    - BANKING & FINANCE
    - BANKS - COVERED (CANADIAN)
    - BANKS (CANADIAN)
    - PRIVATE PLACEMENTS - BANKING
    - YANKEE BONDS - FINANCIAL
    - PREFERRED SHARES (DEBT) FINANCIAL
    - TRUST PREFERRED SHARES - FINANCIAL

palestine:
  ticker:
    - AVGL
    - BKNG
    - CEL
    - DELT
    - DLEA
    - DLEKG
    - DK
    - DRAL
    - EDR
    - EXPE
    - FIBI
    - GIS
    - LLL
    - MTRX
    - MSI
    - MZTF
    - PZOL
    - RMAX
    - SPEN
    - TRIP
